name: pizza_ja
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  get: 4.3.8
  group_radio_button: ^1.1.0
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
